server:
  port: 9898
  servlet:
    session:
      cookie:
        name: AUTH_SERVER_SESSION_ID
        http-only: true

spring:
  application:
    name: hasp-auth-server
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML #LEGACYHTML5
  data:
    redis:
      host: ${REDIS_HOST:127.0.0.1}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      timeout: 3000ms
      connect-timeout: 5000
      client-type: LETTUCE
      lettuce:
        pool:
          max-wait: 800ms
          max-active: 5
          min-idle: 3
          max-idle: 5
  security:
    oauth2:
      authorizationserver:
        multiple-issuers-allowed: false
        issuer: ${OAUTH2_ISSUER:http://127.0.0.1:9898}
        endpoint:
          authorizationUri: ${OAUTH2_AUTHORIZATION_URI:/oauth2/authorize}
          deviceAuthorizationUri: ${OAUTH2_DEVICE_AUTHORIZATION_URI:/oauth2/device_authorization}
          deviceVerificationUri: ${OAUTH2_DEVICE_VERIFICATION_URI:/oauth2/device_verification}
          tokenUri: ${OAUTH2_TOKEN_URI:/oauth2/token}
          jwkSetUri: ${OAUTH2_JWK_SET_URI:/oauth2/jwks}
          tokenRevocationUri: ${OAUTH2_TOKEN_REVOCATION_URI:/oauth2/revoke}
          tokenIntrospectionUri: ${OAUTH2_TOKEN_INTROSPECTION_URI:/oauth2/introspect}
          oidc:
            logoutUri: ${OAUTH2_LOGOUT_URI:/connect/logout}
            clientRegistrationUri: ${OAUTH2_CLIENT_REGISTRATION_URI:/connect/register}
            userInfoUri: ${OAUTH2_USER_INFO_URI:/userinfo}

springdoc:
  show-login-endpoint: true
  enable-spring-security: true
  show-oauth2-endpoints: true
  api-docs:
    enabled: true
  swagger-ui:
    tagsSorter: alpha
    use-root-path: true
    display-request-duration: true
    doc-expansion: none
    show-Extensions: true
    show-Common-Extensions: true
    disable-swagger-default-url: false

hasp:
  data:
    type: ${HASP_DATA_TYPE:memory} # 动态配置数据类型(memory、remote)，默认为 memory
  cert:
    dir: ${CERT_DIR:/certs} # 动态配置证书目录

justauth:
  enabled: true
  type:
    WECHAT_OPEN:
      client-id: ${WECHAT_OPEN_CLIENT_ID:xxx}
      client-secret: ${WECHAT_OPEN_CLIENT_SECRET:xxx}
      redirect-uri: ${WECHAT_OPEN_REDIRECT_URI:http://127.0.0.1:9898/oauth2/federated/callback/wechat_open}
    GITEE:
      client-id: ${GITEE_CLIENT_ID:xxx}
      client-secret: ${GITEE_CLIENT_SECRET:xxx}
      redirect-uri: ${GITEE_REDIRECT_URI:http://127.0.0.1:9898/oauth2/federated/callback/gitee}
    GITHUB:
      client-id: ${GITHUB_CLIENT_ID:xxx}
      client-secret: ${GITHUB_CLIENT_SECRET:xxx}
      redirect-uri: ${GITHUB_REDIRECT_URI:http://127.0.0.1:9898/oauth2/federated/callback/github}
  cache:
    type: ${CACHE_TYPE:custom}
    prefix: ${CACHE_PREFIX:oauth2_federated_state:}
    timeout: ${CACHE_TIMEOUT:10m}

logging:
  config: classpath:logback/logback-spring.xml
  level:
    root: info
    org.springframework.web: TRACE
    org.springframework.security: TRACE
    org.springframework.security.oauth2: TRACE
